// w2_Vue/myvue/src/components/TodoContent.vue
<template>
  <table class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">待办事项</th>
        <th scope="col">是否完成</th>
        <th scope="col">操作</th>
      </tr>
    </thead>
    <tbody>
      <!-- <todo-item></todo-item> -->
      <!-- <tr is="todo-item" :key="item.id" v-for="(item,idx) in datalist" :item="item" :idx="idx"></tr> -->
      <TodoItem :key="item.id" v-for="(item,idx) in datalist" :item="item" :idx="idx" />
    </tbody>
  </table>
</template>
<script>
import TodoItem from './TodoItem'
export default {
  // 接收父组件传入的数据
  props: ["datalist"],
  data() {
    return {
      
    };
  },
  components: {
    TodoItem,
  },
};
</script>

// w5_React/src/components/TodoList/TodoContent.js
import React from 'react';

import TodoItem from './TodoItem';

function TodoContent({datalist}) {
    console.log('TodoContent=',datalist)
    return (
        <table style={{ width: '100%' }} className="todo-content">
            <thead>
                <tr>
                    <th>#</th>
                    <th>待办事项</th>
                    <th>是否完成</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {
                    datalist.map((item,idx)=><TodoItem index={idx} data={item} key={item.id}/>)
                }
            </tbody>
        </table>
    )
}

export default TodoContent
